workflows:
  ons-android-release:
    name: Ons Android Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: 1. ادخل فولدر أُنس
        script: |
          cd "أُنس"
      - name: 2. نزل الباكدجات
        script: |
          flutter clean
          flutter pub get
      - name: 3. ابني ال apk
        script: |
          flutter build apk --split-per-abi --release
    artifacts:
      - "أُنس/build/app/outputs/flutter-apk/*.apk"